### ISSUE TITLE
getWilayat not working properly, the same with searchWilayatByName

### ISSUE THREAD

**Issue by mbenyoub** [dfourcfive/dzair_data_usage#2]
some wilayat does not satisfy the conditions in the getWilayat methode , 
example wilayat not retrieved: `Alger`, `Illizi`

in the case of `illizi` the data is not correct
in the case of Alger , the condition is not correct because commune name is `Alger centre` , and daira is `sidi m'hamed`

in total I think there is problem with 6 wilayat

**Comment by dfourcfive** [comment]
Hello benyoub , thank you for reporting the issue , I'll try to check what is not right with the functions 
It would be great if you can write down the other missing wilaya data,
plus the searchWilayaByName input and the expected result
thank you.

**Comment by dfourcfive** [comment]
the package now has been updated.
I'll close this issue and wait for the analysis to complete.
for any other issues make sure to report them and thank you.
